name: Run my python
on:
    push:

jobs:
    build: 
        name: do job1
        runs-on: ubnutu-latest #ubnutu為linux常用的版本
        steps:
        - uses: actions/checkout@v2
        - name: Run test.py
          run:
                python3 test.py
    