#設定github自動執行的動作

name: Run my python
on:
    push:

jobs:
    build: 
        name: do job1
        runs-on: ubuntu-latest #ubuntu為lunix
        steps:
        - uses: actions/checkout@v2
        #- name: Install package
         # run:
            #pip3 install mediapipe #pip3其中的3是指python3，因為現在是用python 3版本，之前的版本已經被廢除
        - name: Run sent mail py
          run: 
            python3 send_mail_test_2_receiver.py
    bulid2:
          name: do job2
          runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v2
          - name: Run test 2 py
            run:
              python3 test2.py
           
    